# Colour scheme

  PROMPT_COLOR1=${1:-'red'}     # hyphens
  PROMPT_COLOR2=${2:-'green'}   # current directory
  PROMPT_COLOR3=${3:-'red'}     # user@host
  PROMPT_COLOR4=${4:-'white'}   # user input
  PROMPT_COLOR5="%B%F{black}"   # @ 


# params for prompt

  PROMPT_LEFT_PAREN="%B%F{white}["
  PROMPT_RIGHT_PAREN="%B%F{white}]"
  RETURN_LINE=$'\n'
  VERTICAL_LINE="%B%F{red}│"
  SPACE=" "

# Prompt gfx 

  if [[ ${LC_ALL:-${LC_CTYPE:-$LANG}} = *UTF-8* ]]; then
    PROMPT_GFX_TLC=$'\xe2\x95\x94'  
    PROMPT_GFX_MLC=$'\xe2\x95\xa0'  
    PROMPT_GFX_MVC=$'\xe2\x95\x91'
    PROMPT_GFX_BLC=$'\xe2\x95\x9a'  
    PROMPT_GFX_HYPHEN=$'\xe2\x95\x90'
  else
    PROMPT_GFX_TLC=$'\xda'
    PROMPT_GFX=$'\xc3'
    PROMPT_GFX_BLC=$'\xc0'
    PROMPT_GFX_HYPHEN=$'\xc4'
  fi

  PROMPT_GFX_TOP_BOX="%B%F{$PROMPT_COLOR1}${PROMPT_GFX_TLC}%b%F{$PROMPT_COLOR1}${PROMPT_GFX_HYPHEN}"
  PROMPT_GFX_BOTTOM_BOX="%B%F{$PROMPT_COLOR1}${PROMPT_GFX_BLC}${PROMPT_GFX_HYPHEN}%b%F{$PROMPT_COLOR1}"
  PROMPT_GFX_MIDDLE_BOX="%B%F{$PROMPT_COLOR1}${PROMPT_GFX_MLC}%b%F{$PROMPT_COLOR1}${PROMPT_GFX_HYPHEN}"


# Params for git

  ZSH_GIT_PROMPT_FORCE_BLANK=1
  ZSH_GIT_PROMPT_SHOW_UPSTREAM="no"
  ZSH_THEME_GIT_PROMPT_PREFIX="$RETURN_LINE$PROMPT_GFX_MIDDLE_BOX$PROMPT_GFX_HYPHEN %B%F{white}Git on branch ["
  ZSH_THEME_GIT_PROMPT_SUFFIX="%B%F{white}]"
  ZSH_THEME_GIT_PROMPT_SEPARATOR="%B%F{white}] ["
  ZSH_THEME_GIT_PROMPT_BRANCH="%{$fg_bold[cyan]%}"
  ZSH_THEME_GIT_PROMPT_UPSTREAM_SYMBOL="%{$fg_bold[yellow]%}↻ "
  ZSH_THEME_GIT_PROMPT_UPSTREAM_PREFIX="%{$fg[yellow]%} ⤳ "
  ZSH_THEME_GIT_PROMPT_UPSTREAM_SUFFIX=""
  ZSH_THEME_GIT_PROMPT_DETACHED="%{$fg_no_bold[cyan]%}:"
  ZSH_THEME_GIT_PROMPT_BEHIND="%{$fg_no_bold[cyan]%}↓"
  ZSH_THEME_GIT_PROMPT_AHEAD="%{$fg_no_bold[cyan]%}↑"
  ZSH_THEME_GIT_PROMPT_UNMERGED="%{$fg[red]%} Unmerged✖"
  ZSH_THEME_GIT_PROMPT_STAGED="%{$fg[green]%}●"
  ZSH_THEME_GIT_PROMPT_UNSTAGED="%{$fg[red]%}✚"
  ZSH_THEME_GIT_PROMPT_UNTRACKED="%{$fg[white]%}…"
  ZSH_THEME_GIT_PROMPT_STASHED="%{$fg[blue]%}⚑"
  ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg_bold[green]%}✔"



# Create Prompt
  
  PROMPT_DIR="%B%F{$PROMPT_COLOR2}%~%b%F{$PROMPT_COLOR1}"
  PROMPT_USER_HOST="%b%F{$PROMPT_COLOR3}%n%B%F{$PROMPT_COLOR3}@%b%F{$PROMPT_COLOR3}%m"
  PROMPT_USER="%b%F{$PROMPT_COLOR3}%n"
  PROMPT_HOST="%B%F{$PROMPT_COLOR2}@%b%F{$PROMPT_COLOR3}%m"
  PROMPT_GIT='%b$(gitprompt)'
  PROMPT_CHAR="%F{white}> "

  PROMPT_LINE_1="$PROMPT_GFX_TOP_BOX$PROMPT_LEFT_PAREN$PROMPT_USER$PROMPT_RIGHT_PAREN%b%F{$PROMPT_COLOR1}$SPACE$PROMPT_LEFT_PAREN$PROMPT_DIR$PROMPT_RIGHT_PAREN%b%F{$PROMPT_COLOR1}$PROMPT_GIT"
  PROMPT_LINE_2="$RETURN_LINE%B%F{$PROMPT_COLOR1}$PROMPT_GFX_MVC"
  PROMPT_LINE_3="$RETURN_LINE$PROMPT_GFX_BOTTOM_BOX$PROMPT_GFX_HYPHEN%B%F{white}%B%F{white}$PROMPT_CHAR"


# Create Prompt
  PROMPT="$PROMPT_LINE_1$PROMPT_LINE_2$PROMPT_LINE_3"

